name: zto
description: Annotation-based DTO validation and OpenAPI schema generation for
  Dart server-side.
version: 0.1.0

repository: https://github.com/eduardohr-muniz/artizan_packages
homepage: https://github.com/eduardohr-muniz/artizan_packages/tree/main/zto
documentation: https://github.com/eduardohr-muniz/artizan_packages/blob/main/zto/README.md
issue_tracker: https://github.com/eduardohr-muniz/artizan_packages/issues

topics:
  - dto
  - validation
  - openapi
  - codegen

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
